global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: "sandbox-nginx"
    static_configs:
      - targets: ["sandbox-nginx:80"]
    metrics_path: /nginx-status

  - job_name: "sandbox-api"
    static_configs:
      - targets: ["sandbox-api:5050"]
    metrics_path: /health
